server:
  port: 8090
spring:
  application:
    name: account
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/bank?createDatabaseIfNotExist=true
    username: internetBank
    password: theSecretPassword
    driver-class-name: org.postgresql.Driver