server:
  port: 8090
spring:
  application:
    name: account
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/bank
    username: internetBank
    password: theSecretPassword
    driver-class-name: org.postgresql.Driver
  zipkin:
    baseUrl: "http://${ZIPKIN_HOST:localhost:9411}"
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'