apiVersion: v1
kind: Namespace
metadata:
  name: mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: microservices
data:
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: 'spring-actuator'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['account-server-svc:8090', 'authorization-server-svc:9092', 'configserver-server-svc:8888', 'customer-server-svc:8080']
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus
  namespace: microservices
  labels:
    app: prometheus
    kubernetes.io/cluster-service: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    kubernetes.io/cluster-service: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - nonResourceURLs: ["/metrics", "/actuator/prometheus"]
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: microservices
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
  namespace: microservices
spec:
  template:
    metadata:
      labels:
        name: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9913'
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.9.0
        imagePullPolicy: "IfNotPresent"
        args:
        - --config.file=/etc/config/prometheus.yml
        - --storage.tsdb.path=/prometheus-data
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        ports:
          - containerPort: 9090
            protocol: TCP
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: prometheus-data
            mountPath: /prometheus-data
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
        - name: prometheus-data
          emptyDir: {}
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: microservices
  labels:
    name: prometheus
spec:
  ports:
    - name: "prometheus"
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    name: prometheus
  sessionAffinity: None
  type: ClusterIP
