apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-server
  namespace: microservices
  labels:
    app: account-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-server
  template:
    metadata:
      labels:
        app: account-server
    spec:
      containers:
        - name: account-server
          image: nerociffer/account:1.4
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: account-configmap
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8090
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}