apiVersion: v1
kind: Service
metadata:
  name: account-server-svc
  namespace: microservices
  labels:
    app: account-server
spec:
  type: ClusterIP
  selector:
    app: account-server
  ports:
    - port: 8090
      targetPort: 8090