apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-configmap
  namespace: microservices
data:
  POSTGRES_HOST: postgres-svc
  AUTHORIZATION_HOST: authorization-server-svc
  ZIPKIN_HOST: zipkin-server-svc:9411
  CONFIG_HOST: configserver-server-svc