apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-server
  namespace: microservices
  labels:
    app: customer-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-server
  template:
    metadata:
      labels:
        app: customer-server
    spec:
      containers:
        - name: customer-server
          image: nerociffer/customer:1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: customer-configmap
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # livenessProbe:
          #     httpGet:
          #       path: /actuator/health
          #       port: 8080
          #     initialDelaySeconds: 15
          #     periodSeconds: 20
          # resources: {}