apiVersion: v1
kind: Service
metadata:
  name: authorization-server-svc
  labels:
    app: authorization-server
spec:
  type: ClusterIP
  selector:
    app: authorization-server
  ports:
    - port: 9092
      targetPort: 9092