apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
  namespace: microservices
  labels:
    app: authorization-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authorization-server
  template:
    metadata:
      labels:
        app: authorization-server
    spec:
      containers:
        - name: authorization-server
          image: jmarquessilva/authorization-server:1.0.3
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: microservices-configmap
          readinessProbe:
            httpGet:
              path: /health
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /health
                port: 9092
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}