apiVersion: v1
kind: Service
metadata:
  name: configserver-server-svc
  namespace: microservices
  labels:
    app: configserver-server
spec:
  type: ClusterIP
  selector:
    app: configserver-server
  ports:
    - port: 8888
      targetPort: 8888
