apiVersion: v1
kind: Service
metadata:
  name: zipkin-server-svc
  namespace: microservices
  labels:
    app: zipkin-server
spec:
  type: ClusterIP
  selector:
    app: zipkin-server
  ports:
    - port: 9411
      targetPort: 9411
